name: on-push
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Install non-go dependencies
        run: sudo apt-get update && sudo apt-get install libgl1-mesa-dev xorg-dev libasound2-dev
      - name: Build linux executable
        run: go build -o michelSpace2000 .
      - name: Build windows executable
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o michelSpace2000.exe .
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            michelSpace2000.exe
            michelSpace2000
          prerelease: true
          draft: true
          name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
